# WARNING - Generated by {fusen} from dev/flat_TTest.Rmd: do not edit by hand # nolint: line_length_linter.

test_that("bio_analyze_t_test works", {
  result <- bio_analyze_t_test(n1 = 30, mean1 = 70, sd1 = 10, 
                           n2 = 30, mean2 = 75, sd2 = 10, 
                           test_type = "two.sample.classique", 
                           alpha = 0.05, alternative = "two.sided")
  
  expect_s3_class(result$t_test, "htest")
  expect_true("p.value" %in% names(result$t_test))
  expect_true("statistic" %in% names(result$t_test))
  expect_type(result$power, "double")
  expect_true(result$power > 0 & result$power <= 1)
  expect_s3_class(result$plot, "gg")
})
